apiVersion: v1
kind: Secret
metadata:
  labels:
    component: velero
  name: cloud-credentials
  namespace: {{VELERO_NAMESPACE}}
type: Opaque
stringData:
  cloud: |
    [default]
    aws_access_key_id={{MINIO_ACCESS_KEY}}
    aws_secret_access_key={{MINIO_SECRET_KEY}}