apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: portworx-csi-node
  namespace: {{NAMESPACE}}
spec:
  selector:
    matchLabels:
      app: portworx-csi-node
  template:
    metadata:
      labels:
        app: portworx-csi-node
    spec:
      serviceAccountName: portworx-csi
      containers:
        - name: node-driver-registrar
          image: {{REGISTRAR_IMAGE}}
          args:
            - "--csi-address=$(ADDRESS)"
            - "--kubelet-registration-path=/var/lib/kubelet/plugins/pxd.portworx.com/csi.sock"
            - "--v=5"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
        - name: portworx-csi
          image: {{PORTWORX_IMAGE}}
          securityContext:
            privileged: true
          args:
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--driver=pxd.portworx.com"
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: pods-mount-dir
              mountPath: /var/lib/kubelet/pods
              mountPropagation: Bidirectional
      volumes:
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/pxd.portworx.com
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory
        - name: pods-mount-dir
          hostPath:
            path: /var/lib/kubelet/pods
            type: Directory
